allow edit_url to search string
emacs-eaf/eaf-browser pull request #9
Opened 2021-08-24 19:10 UTC by taquangtrung

Hi,

I created this PR which allows users to search for a string when editing URL (`e`).

Currently, when a user presses `e` to edit the URL and just type `foo`, then EAF browser will return a blank page.
Using this PR, EAF can allow use to search for the string `foo` by using the default search engine.

This PR is accompanied by another PR in the main EAF framework.

Here, I split `eaf-search-it` into 2 functions `eaf--create-search-url` and `eaf-search-it`.

The function `eaf--create-search-url` will be called by the main EAF webengine to create the search string.

Could you advise if this feature is useful and can be merged?

Thanks!

2021-08-24 23:37 UTC, manateelazycat commented
Looks https://github.com/emacs-eaf/emacs-application-framework/pull/827

2021-08-25 04:02 UTC, taquangtrung commented
@manateelazycat : I updated the new code. Could you take a look?

2021-08-25 04:41 UTC, manateelazycat requested changes

2021-08-25 04:41 UTC, manateelazycat commented on buffer.py
> +        pass
```pass``` need remove.

2021-08-25 05:06 UTC, taquangtrung commented on buffer.py
> +        pass
I updated it too!

2021-08-25 05:32 UTC, merged

2021-08-25 05:33 UTC, manateelazycat commented
Thanks man!